- name: Remote reboot of host
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: Waiting for host to come back
  local_action: wait_for host={{ ansible_hostname }} port=22 delay=15 timeout=300
  sudo: false

- name: Gather uptime details into result
  shell: echo "Uptime of the server is" && /usr/bin/uptime |awk '{print $3 " " $4}' && echo ", it's been up since " && /usr/bin/uptime |awk '{print $1  }'
  register: result

- name: Display the "result" variable
  local_action: command echo item
  with_items: result.stdout_lines

